# Generated by Django 4.2.9 on 2024-01-30 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('deliver_date', models.DateField(default=datetime.date(2024, 2, 9))),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
