# Generated by Django 4.2.9 on 2024-01-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(default=datetime.date(2024, 2, 10)),
        ),
    ]
