# Generated by Django 4.2.9 on 2024-01-25 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccess', '0002_alter_item_id_alter_order_id_alter_shoppingcart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientaccess.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.IntegerField(),
        ),
    ]
