# Generated by Django 4.2.9 on 2024-02-01 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccess', '0002_alter_order_deliver_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(default=datetime.date(2024, 2, 11)),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
