# Generated by Django 4.2.9 on 2024-01-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccess', '0003_remove_shoppingcart_items_shoppingcart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='item',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.IntegerField(),
        ),
    ]
