# Generated by Django 4.2.9 on 2024-01-25 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientaccess', '0004_alter_shoppingcart_item_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
